version: "3.7"

# docker compose up

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=plans
    volumes:
      - plans_pg_data:/bitnami/postgresql

volumes:
  plans_pg_data:
